DROP TABLE feeds;
DROP TABLE types;
DROP TABLE users;

CREATE TABLE types (
	tid INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(20) NOT NULL,
	PRIMARY KEY(tid)
);

CREATE TABLE users(
	uid VARCHAR(100) NOT NULL,
	modified DATE NOT NULL,
	PRIMARY KEY(uid)
);

CREATE TABLE feeds(
	fid VARCHAR(100),
	uid VARCHAR(100) NOT NULL,
	tid INTEGER NOT NULL,
	postdate DATE,
	time TIME,
	PRIMARY KEY(fid),
	FOREIGN KEY(tid) REFERENCES types(tid),
	FOREIGN KEY(uid) REFERENCES users(uid)
);
